version: '3.3'
services:
  vault:
    build:
      context: ./
      dockerfile: Dockerfile-vault
    hostname: vault
    restart: always
    ports:
    - "443:5000"
    cap_add:
      - IPC_LOCK
    volumes:
    - logs_volume:/var/log

volumes:
  logs_volume: {}